"use client";
import Link from "next/link";
import { useState } from "react";
import { PLAYER_OBLIGATIONS, PLAYER_OBLIGATIONS_LABEL } from "@/lib/studContractDisclosures";
export function ManualStudContractRequest(props: { sireDogId: string; damDogId: string }) {
  const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); const [submitted, setSubmitted] = useState(false); const [contractId, setContractId] = useState<string | null>(null); const [acknowledged, setAcknowledged] = useState(false);
  async function requestApproval() { setPending(true); setMessage(""); try { const response = await fetch("/api/stud-contracts/manual", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...props, playerObligationsAcknowledged: acknowledged }) }); const data = await response.json(); setMessage(data?.message ?? data?.error ?? "Unable to request Stud Approval."); setSubmitted(response.ok && data?.ok); setContractId(typeof data?.contract?.id === "string" ? data.contract.id : null); } catch { setMessage("Unable to request Stud Approval."); } finally { setPending(false); } }
  return <section className="theme-card mt-4 rounded-2xl p-4"><h2 className="theme-heading text-lg font-semibold">Manual Approval</h2><p className="theme-copy mt-2 text-sm">Owner approval is required. The request remains open for 24 real hours, does not reserve the sire, and charges no fee unless approval and breeding later succeed.</p><p className="theme-copy mt-3 text-sm">{PLAYER_OBLIGATIONS}</p><label className="theme-copy mt-3 flex items-start gap-3 text-sm"><input type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} className="mt-1 h-4 w-4" /> <span>{PLAYER_OBLIGATIONS_LABEL}</span></label><div className="mt-3 flex flex-wrap gap-2"><button type="button" className="theme-primary-button rounded-xl px-4 py-2 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-60" onClick={requestApproval} disabled={pending || submitted || !acknowledged} aria-busy={pending}>{pending ? "Requesting…" : submitted ? "Stud approval pending" : "Request Stud Approval"}</button>{contractId ? <><Link href={`/stud-contracts/${contractId}`} className="theme-secondary-button rounded-xl px-4 py-2 text-sm font-semibold">Open Contract</Link><Link href="/stud-contracts" className="theme-secondary-button rounded-xl px-4 py-2 text-sm font-semibold">My Stud Contracts</Link></> : null}</div>{message ? <p className="theme-copy mt-3 text-sm" role="status" aria-live="polite">{message}</p> : null}</section>;
}
