import { NextResponse } from "next/server";
import {
  buildPasswordResetUrl,
  createPasswordResetToken
} from "@/lib/passwordReset";
import { sendPasswordResetEmail } from "@/lib/passwordResetEmail";
import { getAppBaseUrl } from "@/lib/appBaseUrl";

const GENERIC_MESSAGE =
  "If an account exists for that email, a password reset link has been sent.";

function successResponse(resetUrl?: string) {
  return NextResponse.json({
    ok: true,
    message: GENERIC_MESSAGE,
    // Local development can expose the link for testing. Production links are
    // delivered only by email or generated by the support-only script.
    ...(process.env.NODE_ENV !== "production" && resetUrl ? { resetUrl } : {})
  });
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const email = String(body.email ?? "").trim();

    if (!email) {
      return NextResponse.json({ error: "Email is required." }, { status: 400 });
    }

    const reset = await createPasswordResetToken({ email });
    if (!reset) return successResponse();

    const resetUrl = buildPasswordResetUrl(getAppBaseUrl(request), reset.token);

    try {
      const delivered = await sendPasswordResetEmail({
        to: reset.email,
        resetUrl
      });

      if (!delivered) {
        console.warn(
          "Password reset requested, but email delivery is not configured."
        );
      }
    } catch (error) {
      // Recovery requests should not reveal delivery details or account
      // existence to the browser. The server log still records the failure.
      console.error("Unable to deliver password reset email.", error);
    }

    return successResponse(resetUrl);
  } catch {
    return NextResponse.json({ error: "Invalid request." }, { status: 400 });
  }
}
