import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const root = join(process.cwd(), "../.."); const source = (path: string) => readFileSync(join(root, path), "utf8");
const page = source("apps/web/app/test/support-sandbox/page.tsx"); const client = source("apps/web/components/test/SupportSandboxTestClient.tsx"); const clearPending = source("apps/web/app/api/test/support-sandbox/clear-pending/route.ts"); const subscriptionRoute = source("apps/web/app/api/support/subscriptions/route.ts");
assert.ok(page.includes("getSessionUserId") && page.includes('redirect("/login")'));
assert.ok(page.includes("CURRENT_SUPPORT_STATUSES"), "harness uses the canonical current-support statuses");
assert.ok(page.includes("getPayPalEnvironment") && page.includes('getPayPalEnvironment() === "sandbox"'), "harness permits controls only in the canonical sandbox environment");
assert.ok(page.includes("Sandbox support testing is unavailable while PayPal is configured for Live."), "live and invalid environments render a read-only unavailable message");
assert.ok(page.includes('status: { in: CURRENT_SUPPORT_STATUSES }'), "current query includes active support states");
assert.ok(page.includes("providerSubscriptionId") && page.includes("firstSupportedAt"), "harness selects safe stored subscription audit fields");
assert.ok(client.includes('fetch("/api/support/subscriptions"'));
assert.ok(client.includes('JSON.stringify({ tier: "BRONZE" })'));
assert.ok(!client.includes('JSON.stringify({ tier: "SILVER" })') && !client.includes('JSON.stringify({ tier: "GOLD" })'), "harness creation remains Bronze-only");
assert.ok(client.includes("Create Bronze Subscription") && client.includes("Continue to PayPal Sandbox Approval"));
assert.ok(client.includes('currentSubscription.status === "PENDING"'), "only pending subscriptions show the recovery control");
assert.ok(client.includes("sandbox subscription is {currentSubscription.status} in ShowRing."), "current canonical status is displayed");
assert.ok(!client.includes("initialPending"), "all current states are rendered from the stored subscription");
assert.ok(clearPending.includes('getPayPalEnvironment() === "sandbox"'), "sandbox reset rejects live before any lookup or provider mutation");
assert.ok(clearPending.includes("Sandbox support testing is unavailable while PayPal is configured for Live."), "sandbox reset returns a safe unavailable response");
assert.ok(!subscriptionRoute.includes("getPayPalEnvironment"), "normal subscription route remains environment-selected through the support service");
console.log("Support sandbox harness checks passed.");
