import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = process.cwd().endsWith(join("apps", "web")) ? resolve(process.cwd(), "..", "..") : process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");
const page = source("apps/web/app/dogs/[dogId]/page.tsx");
const panel = source("apps/web/components/dogs/ManageDogPanel.tsx");
const health = source("apps/web/components/dogs/DogProfileHealthActions.tsx");
const grooming = source("apps/web/components/dogs/DogProfileGroomingManagement.tsx");
const shows = source("apps/web/components/dogs/DogProfileShowsManagement.tsx");
const planning = source("apps/web/components/dogs/DogProfilePrivatePlanning.tsx");

assert.doesNotMatch(page, /DogProfileDashboard/, "production profile no longer renders the compatibility dashboard");
assert.match(panel, /Identity[\s\S]*Kennel[\s\S]*Breeding[\s\S]*Grooming[\s\S]*Shows[\s\S]*Stud[\s\S]*Market/, "Manage Dog groups remain exact");
assert.doesNotMatch(panel, /Private|Health/, "Manage Dog has no Private or Health group");
assert.match(health, /HealthTestingPanel/, "Health retains the real health testing component");
assert.match(health, /brucellosis-screening/, "Health retains the brucellosis route");
assert.match(grooming, /Manage Grooming/, "Grooming has its approved management entry point");
assert.match(grooming, /self-groom[\s\S]*Offer for Outside Grooming/, "Grooming retains real operations");
assert.match(shows, /currentEntriesCount[\s\S]*Pull entry/, "Shows retains current entries and Pull Entry");
assert.match(page, /EmergencyVetCarePanel[\s\S]*ReproductiveEmergencyPanel[\s\S]*DogProfileReadSections/, "urgent panels remain outside Manage Dog before read sections");
assert.match(planning, /Private Kennel Notes[\s\S]*DogPrivateNotesEditor/, "private planning retains notes under its final section");
assert.match(page, /canManage=\{viewerContext\.canManage && header\.lifecycleState === "ALIVE"\}/, "deceased dogs cannot order health actions");
assert.match(page, /actions\.canBuyActiveListing && saleListing/, "Buy Dog remains conditional");
assert.match(page, /actions\.canUseActiveStudListing && studListing/, "Use at Stud remains conditional");
assert.ok(page.indexOf('aria-label="Kennel run dog navigation"') < page.indexOf('aspect-[4/3]'), "Kennel Run navigation is above the hero media");
assert.doesNotMatch(page, /Show Profile|DogStatusBadges|Legacy Producer|Health Clear/, "hero removes production-only label and badge clutter");
assert.doesNotMatch(page, /href=\{`\/dogs\/\$\{header\.dogId\}\/ribbon-room`\}/, "hero no longer duplicates Ribbon Room");
assert.match(source("apps/web/components/dogs/DogProfileReadSections.tsx"), /Ribbon Room/, "Show Career retains Ribbon Room");
assert.match(page, /breedName\} · COLOR · \{header\.sexLabel\}/, "hero preserves the approved breed/color/sex identity line");
assert.match(page, /Registration[\s\S]*Game Age[\s\S]*Owner[\s\S]*Breeder[\s\S]*Kennel Run[\s\S]*Health/, "hero has the approved fact grid");
assert.match(page, /grid gap-x-8 gap-y-0 border-b/, "hero uses the open two-column document layout");
assert.match(page, /lg:grid-cols-\[minmax\(0,1fr\)_minmax\(0,1\.05fr\)\]/, "hero uses the prototype desktop two-column breakpoint and proportions");
assert.match(page, /<div className="order-1">[\s\S]*aspect-\[4\/3\][\s\S]*<div className="order-2 max-w-2xl">/, "media and identity are direct desktop hero siblings");
assert.match(page, /relative mt-6 flex flex-wrap gap-3/, "hero actions use the prototype-sized wrapping action row");
assert.match(panel, /lg:absolute lg:right-0 lg:top-full/, "Manage Dog overlays from the action row at desktop widths");
assert.doesNotMatch(page, /dog-profile-design\/fixture|prototypeCurrentShowEntries/, "production does not import prototype data");

console.log("Dog Profile Manage Dog Stage 2B checks passed.");
