import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const root = process.cwd().endsWith(join("apps", "web")) ? resolve(process.cwd(), "..", "..") : process.cwd();
const source = (path: string) => readFileSync(join(root, path), "utf8");
const page = source("apps/web/app/test/dog-profile-design/page.tsx");
const fixture = source("apps/web/app/test/dog-profile-design/fixture.ts");

assert.match(page, /href="\/breed-art"/, "missing-art state uses the established Breed Art route");
assert.match(page, /label="Show Planner"/, "hero uses Show Planner for future entry planning");
assert.doesNotMatch(page, /label="Enter Show"/, "prototype no longer labels the hero action Enter Show");
assert.match(page, /type PrototypeView = "owner" \| "public" \| "listed" \| "stud" \| "deceased" \| "pregnant"/, "prototype has focused owner, public, market, stud, deceased, and reproductive preview states");
assert.match(page, /!isDeceased && isOwner/, "owner hero controls are suppressed for public and deceased views");
assert.match(page, /!isDeceased && canBuyDog/, "Buy Dog is conditional on the listed public state");
assert.match(page, /!isDeceased && canUseAtStud/, "Use at Stud is conditional on the published Stud Offer state");
assert.match(page, /action=\{isOwner \? <PrototypeButton label="Order Health Tests"/, "owner-only Health controls are suppressed in public views");
assert.match(page, /Deceased · Age at death 4y 2w/, "deceased preview uses static age-at-death presentation");
assert.match(page, /Alive · Pregnant · Show restricted/, "reproductive preview makes pregnancy and show restriction prominent");
assert.match(page, /\{dog\.breed\} · COLOR · \{dog\.sex\}/, "prototype reserves Color in the three-part hero identity line");
assert.match(page, /Dog Profile Preview/, "prototype uses player-facing preview copy");
assert.match(page, /Upcoming Dog Profile/, "prototype identifies the upcoming player experience");
assert.match(page, /Buttons and statuses on this page are examples only and do not affect the game\./, "prototype explains that its controls are non-gameplay examples");
assert.match(page, /View Without Breed Art/, "prototype uses player-facing missing-art preview copy");
assert.match(page, /Preview Emergency State/, "prototype uses player-facing emergency-preview copy");
assert.match(page, /TraitLine/, "prototype reuses the established trait slider component");
assert.match(page, /precision=\{3\}/, "prototype preserves three-decimal visible-category presentation");
assert.match(page, /PHENOTYPE_HEALTH_SEVERITY_TEXT_CLASSES/, "prototype reuses the established health result text-class mapping");
assert.match(page, /valueClassName: PHENOTYPE_HEALTH_SEVERITY_TEXT_CLASSES\[severity\]/, "only prototype Health result values receive the established severity class");
assert.match(page, /className=\{`text-sm font-semibold \$\{row\.valueClassName \?\? "theme-heading"\}`\}/, "health result values use their semantic class instead of the neutral theme-heading class");
assert.match(page, /<SummarySection title="Show Career".*action=\{<div className="flex flex-wrap gap-2"><PrototypeButton label="View Full Show Record".*<PrototypeButton label="Ribbon Room"/, "Show Career presents the locally mocked Ribbon Room action beside the full record action");
assert.match(page, /ManageShowsGroup entries=\{prototypeCurrentShowEntries\}/, "Manage Dog includes its dedicated Shows management group");
assert.match(page, /aria-controls="prototype-current-entries"/, "Manage Shows exposes an accessible current-entry expander");
assert.match(page, /\{entries\.length\} current entries/, "Manage Shows displays the current-entry count");
assert.match(fixture, /showName: "Copper Valley Kennel Club"/, "prototype fixture includes fictional current entries");
assert.match(page, /label="Pull entry"/, "fictional current entries include local Pull entry controls");
assert.doesNotMatch(page, /showEntry\.service|\/api\/.*show-entry|\/api\/show-entries/, "prototype has no production show-entry service or API dependency");
assert.doesNotMatch(page, /@\/lib\/db|@\/server\/services|fetch\(/, "prototype has no database, service, or API dependency");
assert.match(page, /Manage Dog/, "prototype includes the local Manage Dog control");
assert.match(page, /aria-expanded=\{manageDogOpen\}/, "Manage Dog exposes expanded state");
assert.match(page, /title="Breeding" actions=\{\["Breed", "Breeding participation"\]\}/, "Manage Dog contains the Breeding actions");
assert.match(page, /ManageGroomingGroup/, "Manage Dog contains the Grooming doorway");
assert.match(page, /aria-controls="prototype-grooming-management"/, "Manage Grooming exposes an accessible local expander");
assert.match(page, /Stud Worksheet/, "Manage Dog contains the Stud Worksheet destination");
assert.match(page, /aria-label="Kennel run dog navigation"/, "owner preview includes Kennel Run navigation");
assert.match(page, /isOwner \? <nav aria-label="Kennel run dog navigation"/, "Kennel Run navigation is owner-only");
assert.match(page, /Private Kennel Notes/, "Breeding and Production contains the owner-only private-note destination");
assert.doesNotMatch(page, /Groom Aster/, "Ring Evaluation has no duplicate prominent Groom action");
assert.match(page, /Emergency veterinary care required/, "prototype keeps urgent care visible outside Manage Dog");
assert.doesNotMatch(fixture, /genotype|geneticsVersion|traitHead|traitForequarters|traitHindquarters|traitGait|traitCoat|traitSize|traitTemperament|traitShowShine|traitFeet|traitTopline/, "fixture contains no hidden Dog trait fields");
assert.match(fixture, /Demo's Ringbright Aster/, "prototype carries forward the guide dog's player-facing identity");

console.log("Dog Profile design prototype checks passed.");
