export const exampleDog = {
  displayName: "Aster",
  registeredName: "Demo's Ringbright Aster",
  regNumber: "DT713761101",
  breedName: "Dachshund",
  sexLabel: "Female",
  ageLabel: "2y 4w",
  originLabel: "Foundation Dog",
  lifecycleLabel: "Alive",
  marketLabel: "Not for sale",
  showEligibilityLabel: "Eligible",
  breedingEligibilityLabel: "Eligible",
};

export const exampleVisibleCategories = [
  {
    key: "typeExpression",
    label: "Type & Expression",
    numericScore: 11.2,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
  },
  {
    key: "structureBalance",
    label: "Structure & Balance",
    numericScore: 9.4,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
  },
  {
    key: "movement",
    label: "Movement",
    numericScore: 12.1,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
  },
  {
    key: "coatPresentation",
    label: "Coat & Presentation",
    numericScore: 8.8,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
  },
  {
    key: "temperamentRingBehavior",
    label: "Temperament",
    numericScore: 10.6,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
  },
  {
    key: "conditioningHandling",
    label: "Conditioning & Handling",
    numericScore: 7.5,
    min: 0,
    ideal: 10,
    max: 10,
    leftLabel: "0",
    centerLabel: "",
    rightLabel: "10 optimized",
  },
] as const;
