import type { DogProfileDto } from "@/server/mappers/dog.mapper";

export const exampleVisibleCategories = [
  {
    key: "typeExpression",
    label: "Type & Expression",
    numericScore: 11.2,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
    scaleMeaning: "Directional ring type expression with 10 near ideal.",
  },
  {
    key: "structureBalance",
    label: "Structure & Balance",
    numericScore: 9.4,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
    scaleMeaning: "Directional outline and balance with 10 near ideal.",
  },
  {
    key: "movement",
    label: "Movement",
    numericScore: 12.1,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
    scaleMeaning: "Directional gait impression with 10 near ideal.",
  },
  {
    key: "coatPresentation",
    label: "Coat & Presentation",
    numericScore: 8.8,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
    scaleMeaning: "Directional coat and presentation with 10 near ideal.",
  },
  {
    key: "temperamentRingBehavior",
    label: "Temperament",
    numericScore: 10.6,
    min: 0,
    ideal: 10,
    max: 20,
    leftLabel: "Under ideal",
    centerLabel: "10 ideal",
    rightLabel: "Over ideal",
    scaleMeaning: "Directional temperament and ring behavior with 10 near ideal.",
  },
  {
    key: "conditioningHandling",
    label: "Conditioning & Handling",
    numericScore: 7.5,
    min: 0,
    ideal: 10,
    max: 10,
    leftLabel: "0",
    centerLabel: "",
    rightLabel: "10 optimized",
    scaleMeaning: "Current preparation and handling, where higher is better.",
  },
] as const;

export const exampleCurrentEpoch = 18624;

export const exampleDogProfile: DogProfileDto = {
  header: {
    dogId: "guide-example-aster",
    displayName: "Demo's Ringbright Aster",
    registeredName: "Demo's Ringbright Aster",
    callName: "Aster",
    visibleTitlePrefix: "CH",
    visibleTitleSuffix: null,
    breedName: "Dachshund",
    regNumber: "DT713761101",
    sex: "F",
    sexLabel: "Female",
    ageHours: 2912,
    ageLabel: "2y 4w",
    lifecycleState: "ALIVE",
    lifecycleLabel: "Alive",
    originLabel: "Foundation Dog",
    badges: [
      { code: "CH", label: "Champion", tone: "green" },
      { code: "HEALTH", label: "Full health clearance", tone: "green" },
      { code: "OWNED", label: "Example profile", tone: "purple" },
    ],
  },
  currentRun: {
    runId: "guide-example-main-run",
    name: "Main Show Team",
  },
  snapshot: {
    owner: {
      kennelId: "guide-example-kennel",
      name: "Demo Kennel",
      slug: "demo-kennel",
    },
    breeder: null,
    sire: {
      dogId: "guide-example-sire",
      displayName: "Foundation Sire",
      profileUrl: "/start-up-guide/example-dog",
    },
    dam: {
      dogId: "guide-example-dam",
      displayName: "Foundation Dam",
      profileUrl: "/start-up-guide/example-dog",
    },
    originLabel: "Foundation Dog",
    marketLabel: "Not for sale",
    canShow: true,
    canBreed: true,
    showEligibilityLabel: "Eligible",
    breedingEligibilityLabel: "Eligible",
    groomingLabel: "Needs grooming",
    healthTestingSummary: {
      completedCount: 4,
      totalCount: 4,
      label: "4/4 tests complete",
      badgeStatus: "green",
      hasFullClearance: true,
    },
    coatConditionDisplay: "8.80",
  },
  qualityAndPresentation: {
    visibleCategories: [...exampleVisibleCategories],
  },
  titlesAndShowCareer: {
    currentTitleCode: "CH",
    isChampionFinished: true,
    pointsEarned: 16,
    pointsRequired: 15,
    majorsEarned: 2,
    majorsRequired: 2,
    pointsRemaining: 0,
    majorsRemaining: 0,
    pointRequirementMet: true,
    majorRequirementMet: true,
    grandPointsEarned: 8,
    grandPointsRequired: 25,
    grandMajorsEarned: 1,
    grandMajorsRequired: 3,
    grandChampionDefeatShowCount: 1,
    grandChampionDefeatShowRequired: 3,
    grandRequirementMet: false,
    grandMajorRequirementMet: false,
    grandDefeatRequirementMet: false,
    isGrandChampionFinished: false,
    grandCompletedAtShowDayId: null,
    grandCompletedAtEpoch: null,
    grandStatusLabel: "Grand Champion in progress",
    grandPointsLabel: "8/25",
    currentGrandTitleLabel: "Champion",
    nextGrandMilestoneLabel: "Needs 17 GCH points",
    summaryLabel: "Champion finished; Grand Champion progress started.",
    fullShowRecordUrl: "/start-up-guide/example-dog",
    recentPointWins: [
      {
        showDayId: "guide-show-day-3",
        awardCode: "BOB",
        pointsAwarded: 4,
        isMajor: true,
      },
      {
        showDayId: "guide-show-day-2",
        awardCode: "WB",
        pointsAwarded: 3,
        isMajor: true,
      },
    ],
    recentShowResults: [
      {
        resultId: "guide-result-3",
        showId: "guide-show-3",
        showUrl: "/shows",
        showName: "Copper Valley Kennel Club",
        scheduledEpoch: 18480,
        showDateLabel: "Year 3, Week 5",
        showDayNumber: 1,
        districtRegion: "Southwest",
        breedCode2: "DT",
        breedResultUrl: "/shows",
        judgeCode: "J-ARIAS",
        judgeName: "M. Arias",
        judgeProfileUrl: "/judges",
        awardCodes: ["BOB", "G2"],
        pointsAwarded: 4,
        isMajor: true,
        titlePointsDisplay: {
          value: 4,
          track: "GCH",
          label: "GCH pts",
          isMajor: true,
        },
      },
      {
        resultId: "guide-result-2",
        showId: "guide-show-2",
        showUrl: "/shows",
        showName: "Pine Ridge All-Breed",
        scheduledEpoch: 18312,
        showDateLabel: "Year 3, Week 4",
        showDayNumber: 2,
        districtRegion: "Midwest",
        breedCode2: "DT",
        breedResultUrl: "/shows",
        judgeCode: "J-LEE",
        judgeName: "T. Lee",
        judgeProfileUrl: "/judges",
        awardCodes: ["WB"],
        pointsAwarded: 3,
        isMajor: true,
        titlePointsDisplay: {
          value: 3,
          track: "CH",
          label: "CH pts",
          isMajor: true,
        },
      },
      {
        resultId: "guide-result-1",
        showId: "guide-show-1",
        showUrl: "/shows",
        showName: "Desert Classic",
        scheduledEpoch: 18144,
        showDateLabel: "Year 3, Week 3",
        showDayNumber: 1,
        districtRegion: "Southwest",
        breedCode2: "DT",
        breedResultUrl: "/shows",
        judgeCode: "J-PARK",
        judgeName: "E. Park",
        judgeProfileUrl: "/judges",
        awardCodes: ["RWB"],
        pointsAwarded: 0,
        isMajor: false,
        titlePointsDisplay: {
          value: 0,
          track: null,
          label: "pts",
          isMajor: false,
        },
      },
    ],
  },
  healthTesting: {
    completedCount: 4,
    totalCount: 4,
    summaryLabel: "4/4 health tests complete",
    tests: [
      {
        testCode: "HIPS",
        displayName: "Hip Evaluation",
        resultLabel: "Good",
        severityKey: "green",
        healthImpactStatement: "Strong breeding result.",
        testedDateLabel: "Year 3, Week 1",
        isComplete: true,
        minimumAgeLabel: "Available at 2 years",
        isCurrentlyAvailable: true,
        cost: 300,
      },
      {
        testCode: "EYES",
        displayName: "Eye Exam",
        resultLabel: "Normal",
        severityKey: "green",
        healthImpactStatement: "No visible concern on this screening.",
        testedDateLabel: "Year 3, Week 1",
        isComplete: true,
        minimumAgeLabel: "Available now",
        isCurrentlyAvailable: true,
        cost: 150,
      },
      {
        testCode: "CARDIAC",
        displayName: "Cardiac Screening",
        resultLabel: "Normal",
        severityKey: "green",
        healthImpactStatement: "No visible concern on this screening.",
        testedDateLabel: "Year 3, Week 1",
        isComplete: true,
        minimumAgeLabel: "Available now",
        isCurrentlyAvailable: true,
        cost: 175,
      },
      {
        testCode: "PATELLA",
        displayName: "Patella Evaluation",
        resultLabel: "Normal",
        severityKey: "green",
        healthImpactStatement: "No visible concern on this screening.",
        testedDateLabel: "Year 3, Week 1",
        isComplete: true,
        minimumAgeLabel: "Available now",
        isCurrentlyAvailable: true,
        cost: 125,
      },
    ],
    breedingSafetyScreening: [
      {
        screeningCode: "BRUCELLOSIS",
        label: "Brucellosis Screening",
        helperText:
          "Repeatable safety screening used before breeding decisions.",
        isRepeatable: true,
        currentStatusLabel: "Current negative",
        lastResultLabel: "Negative",
        testedAtEpoch: 18576,
        testedAtLabel: "Tested Year 3, Week 5",
        validUntilEpoch: 18744,
        validUntilLabel: "Valid through Year 3, Week 6",
        isCurrentNegative: true,
        isPositiveOrInfected: false,
      },
    ],
    ownerControls: null,
  },
  groomingDetails: {
    weeklyActionsRemaining: 1,
    weeklyActionLimit: 2,
    currentCoatCondition: 8.8,
    netGroomingEffect: -0.2,
    groomingStatus: "Needs grooming",
    listedForOutsideGrooming: false,
    outsideGroomingListingId: null,
    totalHistoricalGain: 3.4,
    totalHistoricalDecay: 1.8,
    canGroom: true,
    groomedThisWeek: false,
    nextGroomingResetEpoch: 18720,
    canOfferOutsideGrooming: true,
    canCancelOutsideGrooming: false,
  },
  activeBreedingAttempt: null,
  breedingAndProduction: {
    breedingEligibilityLabel: "Eligible",
    productionRoleLabel: "Brood bitch",
    activeStudListing: null,
    activeSaleListing: null,
    sireHistory: [],
    damHistory: [
      {
        attemptId: "guide-breeding-1",
        sireDogId: "guide-sire-2",
        sireName: "CH Meadowlark Lowbeam",
        sireUrl: "/start-up-guide/example-dog",
        litterId: "guide-litter-1",
        litterUrl: "/litters",
        breedingDateLabel: "Year 2, Week 6",
        whelpedDateLabel: "Year 2, Week 9",
        puppyCount: 4,
        survivedCount: 4,
        attemptStatusLabel: "Whelped",
      },
    ],
    progeny: [
      {
        dogId: "guide-puppy-1",
        displayName: "Demo's Copper Comet",
        dogUrl: "/start-up-guide/example-dog",
        sexLabel: "Male",
        titleSummary: "Started",
      },
      {
        dogId: "guide-puppy-2",
        displayName: "Demo's Bright Fern",
        dogUrl: "/start-up-guide/example-dog",
        sexLabel: "Female",
        titleSummary: null,
      },
    ],
    championOffspringCount: 0,
    producerMerit: {
      currentMeritLabel: null,
      currentMeritSuffix: null,
      nextMeritLabel: "Producer of Merit",
      progressCurrent: 0,
      progressRequired: 3,
      progressLabel: "0/3 champion offspring",
      highestMeritReached: false,
    },
  },
  pedigree: {
    coiValue: 0,
    coiLabel: "COI: 0.00%",
    generationDepth: 4,
    colorLabel: "Color: Pending",
    healthTestsSummary: "Ancestor health markers available",
    ancestors: [
      {
        dogId: "guide-sire",
        displayName: "Foundation Sire",
        relationship: "Sire",
        profileUrl: "/start-up-guide/example-dog",
        healthStatusMarkers: {
          badgeStatus: "green",
          hasFullClearance: true,
        },
        colorLabel: "Color: Pending",
        detailedHealthResults: [
          {
            testCode: "HIPS",
            displayName: "Hips",
            resultLabel: "Good",
            severityKey: "green",
          },
        ],
        healthSeverityCounts: {
          green: 4,
          yellow: 0,
          red: 0,
        },
      },
      {
        dogId: "guide-dam",
        displayName: "Foundation Dam",
        relationship: "Dam",
        profileUrl: "/start-up-guide/example-dog",
        healthStatusMarkers: {
          badgeStatus: "yellow",
          hasFullClearance: false,
        },
        colorLabel: "Color: Pending",
        detailedHealthResults: [
          {
            testCode: "HIPS",
            displayName: "Hips",
            resultLabel: "Fair",
            severityKey: "yellow",
          },
        ],
        healthSeverityCounts: {
          green: 3,
          yellow: 1,
          red: 0,
        },
      },
      {
        dogId: "guide-grandsire",
        displayName: "Old Creek Compass",
        relationship: "Sire's Sire",
        profileUrl: "/start-up-guide/example-dog",
        healthStatusMarkers: {
          badgeStatus: null,
          hasFullClearance: false,
        },
        colorLabel: "Color: Pending",
        detailedHealthResults: [],
        healthSeverityCounts: null,
      },
      {
        dogId: "guide-granddam",
        displayName: "Willowbank Starling",
        relationship: "Sire's Dam",
        profileUrl: "/start-up-guide/example-dog",
        healthStatusMarkers: {
          badgeStatus: "green",
          hasFullClearance: true,
        },
        colorLabel: "Color: Pending",
        detailedHealthResults: [],
        healthSeverityCounts: {
          green: 4,
          yellow: 0,
          red: 0,
        },
      },
    ],
  },
  entries: null,
  privatePlanning: null,
  emergencyCare: null,
  actions: {
    canName: false,
    canBreed: false,
    canBuyActiveListing: false,
    canUseActiveStudListing: false,
    canOfferForSale: false,
    canEditSaleListing: false,
    canCancelSaleListing: false,
    canOfferAtStud: false,
    canEditStudFee: false,
    canCancelStudListing: false,
    canRehome: false,
    rehomePayout: null,
    canPullEntries: false,
  },
  viewerContext: {
    isAuthenticated: false,
    viewerKennelId: null,
    isOwnedByCurrentKennel: false,
    canManage: false,
    canViewPrivatePlanning: false,
  },
};
