import Link from "next/link";
import { AutomaticStudContractConfirmation } from "@/components/stud-contract/AutomaticStudContractConfirmation";
import { ManualStudContractRequest } from "@/components/stud-contract/ManualStudContractRequest";
import { notFound, redirect } from "next/navigation";
import { db } from "@/lib/db";
import { formatDogDisplayName } from "@/lib/dogNames";
import { RETURN_SERVICE_FINE_PRINT } from "@/lib/studContractDisclosures";
import { getCurrentEpoch } from "@/lib/gameClock";
import { getSessionUserId } from "@/lib/session";
import { getBreedingEligibilityMessage, getIndividualBreedingEligibility } from "@/server/services/breedingEligibility.service";
import { getKennelForUser } from "@/server/services/kennel.service";
import { activePublicStudListingWhere } from "@/server/services/publicStud.service";
import { getCurrentPublishedStudOffersForSires } from "@/server/services/studOffer.service";
import { evaluateCurrentDamAgainstStudContractRequirements } from "@/server/services/studContractEligibility.service";
import { PHENOTYPE_HEALTH_TESTS } from "@showring/rules";

type PageProps = { searchParams?: Promise<{ studListingId?: string | string[]; sireDogId?: string | string[]; damDogId?: string | string[]; source?: string | string[] }> };
const first = (v: string | string[] | undefined) => (Array.isArray(v) ? v[0] : v)?.trim() || null;
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default async function StudContractPage({ searchParams }: PageProps) {
  const userId = await getSessionUserId(); if (!userId) redirect("/login");
  const kennel = await getKennelForUser(userId); if (!kennel) redirect("/onboarding");
  const q = searchParams ? await searchParams : {}; const listingId = first(q.studListingId); const sireId = first(q.sireDogId); const damId = first(q.damDogId);
  if (!listingId || !sireId) notFound();
  const listing = await db.dogListing.findFirst({ where: { id: listingId, ...activePublicStudListingWhere({ dogId: sireId, excludeKennelId: kennel.id }) }, select: { dog: { select: { id: true, callName: true, registeredName: true, regNumber: true, visibleTitlePrefix: true, visibleTitleSuffix: true, breedCode2: true, sex: true, birthEpoch: true, lifecycleState: true, isBreedingActive: true, breed: { select: { name: true } }, ownerKennel: { select: { name: true } } } } } });
  if (!listing || listing.dog.sex !== "M") notFound();
  const offer = (await getCurrentPublishedStudOffersForSires([sireId]))[0] ?? null;
  const latest = await db.breedingAttempt.findFirst({ where: { sireId }, orderBy: [{ createdEpoch: "desc" }, { id: "desc" }], select: { createdEpoch: true } });
  const availability = getIndividualBreedingEligibility({ currentEpoch: getCurrentEpoch(), birthEpoch: listing.dog.birthEpoch, lifecycleState: listing.dog.lifecycleState, sex: listing.dog.sex, latestSireAttemptCreatedEpoch: latest?.createdEpoch ?? null });
  const dam = damId ? await db.dog.findFirst({ where: { id: damId, ownerKennelId: kennel.id }, select: { id: true, callName: true, registeredName: true, regNumber: true, visibleTitlePrefix: true, visibleTitleSuffix: true, breedCode2: true, sex: true, birthEpoch: true, lifecycleState: true, isBreedingActive: true, breedingAttemptsAsDam: { where: { status: { in: ["INITIATED", "PREGNANT"] } }, orderBy: { createdEpoch: "desc" }, take: 1, select: { status: true } }, dammedLitters: { orderBy: { bornEpoch: "desc" }, take: 1, select: { bornEpoch: true } } } }) : null;
  if (damId && !dam) notFound();
  const mismatch = dam && (dam.sex !== "F" || dam.breedCode2 !== listing.dog.breedCode2 || dam.id === sireId);
  const currentEpoch = getCurrentEpoch();
  const damAvailability = dam ? getIndividualBreedingEligibility({ currentEpoch, birthEpoch: dam.birthEpoch, lifecycleState: dam.lifecycleState, sex: dam.sex, activeBreedingAttemptStatus: dam.breedingAttemptsAsDam[0]?.status ?? null, lastWhelpedEpoch: dam.dammedLitters[0]?.bornEpoch ?? null }) : null;
  const contractEligibility = dam && offer ? await evaluateCurrentDamAgainstStudContractRequirements({ damDogId: dam.id, currentEpoch, requirements: { brucellosisNegativeRequired: offer.brucellosisNegativeRequired, healthRequirements: offer.healthRequirements, titleRequirement: offer.titleRequirement } }) : null;
  const pendingManualRequest = dam ? await db.studContract.findFirst({ where: { damDogId: dam.id, sireDogId: sireId, status: "PENDING" }, select: { approvalDeadlineAt: true } }) : null;
  const back = first(q.source) === "plan-a-litter" ? "/plan-a-litter" : first(q.source) === "breed-dog" ? "/breed" : "/studs";
  return <main className="min-h-screen px-6 py-8"><section className="theme-panel mx-auto max-w-3xl rounded-[28px] px-6 py-8"><p className="theme-label text-sm uppercase tracking-[0.22em]">Stud Contract</p><h1 className="theme-heading mt-2 text-4xl font-bold">Stud Contract Terms</h1>
    <section className="theme-card mt-6 rounded-2xl p-4"><h2 className="theme-heading text-lg font-semibold">Sire</h2><p className="theme-copy mt-2">{formatDogDisplayName(listing.dog)} · {listing.dog.breed.name} · {listing.dog.regNumber}</p><p className="theme-copy mt-2 text-sm">Sire availability: {!listing.dog.isBreedingActive ? "Breeding Inactive" : availability.isEligible ? "Available" : availability.reasonCode === "STUD_RECOVERY" ? `Stud Recovery — ${availability.remainingHours} real hours remaining` : getBreedingEligibilityMessage(availability) ?? "Currently unavailable"}</p><Link href={`/dogs/${sireId}`} className="theme-secondary-button mt-3 inline-flex rounded-xl px-3 py-2 text-sm font-semibold">View Dog</Link></section>
    {dam ? <section className="theme-card mt-4 rounded-2xl p-4"><h2 className="theme-heading text-lg font-semibold">Selected Dam</h2><p className="theme-copy mt-2">{formatDogDisplayName(dam)} · {dam.regNumber}</p><p className="theme-copy mt-2 text-sm">Ordinary breeding status: {!dam.isBreedingActive ? "Breeding Inactive" : damAvailability?.isEligible ? "Available" : getBreedingEligibilityMessage(damAvailability!) ?? "Currently unavailable"}</p><p className="theme-copy mt-2 text-sm">{mismatch ? "This dam cannot be paired with this sire." : contractEligibility ? `Contract Requirements: ${contractEligibility.eligible ? "Meets" : "Does not currently meet"}` : "Stud Contract terms are not currently published."}</p>{contractEligibility ? <ul className="theme-copy mt-2 grid gap-1 text-sm"><li>Brucellosis: {contractEligibility.brucellosis.eligible ? "Meets" : contractEligibility.brucellosis.message}</li>{contractEligibility.health.map((item) => <li key={item.healthTestCode}>{item.healthTestLabel}: {item.eligible ? "Meets" : item.message}</li>)}<li>Title: {contractEligibility.title.eligible ? "Meets" : contractEligibility.title.message}</li></ul> : null}</section> : <section className="theme-status-info mt-4 rounded-2xl p-4"><p>Choose an eligible owned dam in the existing planner to see pairing context.</p><Link href="/plan-a-litter" className="theme-secondary-button mt-3 inline-flex rounded-xl px-3 py-2 text-sm font-semibold">Choose a Dam</Link></section>}
    {!offer ? <p className="theme-status-danger mt-4 rounded-2xl p-4" role="status">Stud contract terms are not currently published for this sire.</p> : <section className="theme-card mt-4 rounded-2xl p-4"><h2 className="theme-heading text-lg font-semibold">Published Terms</h2><div className="theme-copy mt-3 grid gap-3 text-sm"><p><b>Compensation:</b> {offer.compensationType === "PUPPY_BACK" ? "Puppy Back" : offer.compensationType === "CASH" ? money.format(offer.cashAmount ?? 0) : `${money.format(offer.cashAmount ?? 0)} + Puppy Back`}</p>{offer.compensationType !== "CASH" ? <><p><b>Puppy-Back Terms:</b> {offer.puppyPickPosition === "SECOND" ? "Second Pick" : "First Pick"} · Required Sex: {offer.puppySex === "MALE" ? "Male" : offer.puppySex === "FEMALE" ? "Female" : "Either"} · Minimum qualifying litter: {offer.minimumLitterSize} puppies born alive at whelping</p><p>Deaths after whelping do not change the contractual count. Selection opens after litter creation and is never automatic. First Pick is due 24 real hours after puppy age; Second Pick gives the dam 24 real hours and the stud owner a fixed birth-plus-48-real-hour deadline, which does not move even if selection starts early. Required sex is mandatory, with no alternate-sex or cash substitution; missed rights are forfeited. A selected puppy&apos;s death may reopen stud selection before Day 56. Puppy-Back failure alone does not create Return Service.</p></> : null}<p><b>Return Service:</b> No-litter: {offer.noLitterReturnService ? "Offered" : "Not offered"}. Small-litter: {offer.smallLitterReturnThreshold === null ? "Not offered" : `${offer.smallLitterReturnThreshold} or fewer puppies born alive at whelping`}.</p><p><b>Dam Requirements:</b> Brucellosis: {offer.brucellosisNegativeRequired ? "Negative required" : "No restriction"}. Title: {offer.titleRequirement === "CH_OR_HIGHER" ? "CH or higher" : offer.titleRequirement === "GCH_OR_HIGHER" ? "GCH or higher" : "No restriction"}. {offer.healthRequirements.map((r) => `${PHENOTYPE_HEALTH_TESTS[r.healthTestCode as keyof typeof PHENOTYPE_HEALTH_TESTS]?.label ?? r.healthTestCode}: ${r.requirementLevel === "GREEN_ONLY" ? "Green only" : r.requirementLevel === "GREEN_OR_YELLOW" ? "Green or Yellow" : "No restriction"}`).join(" · ")}</p><p><b>Approval:</b> {offer.approvalMode === "MANUAL" ? "Manual Approval — individual approval is required; future requests remain open for 24 real hours and do not reserve the sire." : "Automatic Approval — qualifying breedings do not require individual approval from the stud owner."}</p></div></section>}
    {offer ? <section className="theme-card mt-4 rounded-2xl p-4"><h2 className="theme-heading text-lg font-semibold">Return Service and availability</h2><p className="theme-copy mt-2 text-sm">{RETURN_SERVICE_FINE_PRINT}</p></section> : null}
    {dam && offer?.approvalMode === "AUTOMATIC" && !mismatch && contractEligibility?.eligible && damAvailability?.isEligible && availability.isEligible ? <AutomaticStudContractConfirmation studListingId={listingId} sireDogId={sireId} damDogId={dam.id} /> : null}
    {pendingManualRequest ? <section className="theme-status-info mt-4 rounded-2xl p-4" role="status"><p className="font-semibold">Stud approval pending</p><p className="mt-1 text-sm">No breeding or payment has occurred. Decision deadline: {pendingManualRequest.approvalDeadlineAt?.toLocaleString() ?? "Unavailable"}.</p></section> : dam && offer?.approvalMode === "MANUAL" && !mismatch && contractEligibility?.eligible && damAvailability?.isEligible ? <ManualStudContractRequest studListingId={listingId} sireDogId={sireId} damDogId={dam.id} /> : null}
    <Link href={back} className="theme-secondary-button mt-8 inline-flex rounded-2xl px-5 py-3 text-sm font-semibold">Go Back</Link></section></main>;
}
