import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { StudContractReturnServiceAction } from "@/components/stud-contract/StudContractReturnServiceAction";
import { getSessionUserId } from "@/lib/session";
import { getKennelForUser } from "@/server/services/kennel.service";
import { getStudContractHistoryDetail } from "@/server/services/studContractHistory.service";

const dates = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" });
const formatDate = (value: string | null) => value ? dates.format(new Date(value)) : "Not recorded";

export default async function StudContractDetailPage({ params }: { params: Promise<{ contractId: string }> }) {
  const userId = await getSessionUserId(); if (!userId) redirect("/login");
  const kennel = await getKennelForUser(userId); if (!kennel) redirect("/onboarding");
  const { contractId } = await params;
  const contract = await getStudContractHistoryDetail({ kennelId: kennel.id, contractId });
  if (!contract) notFound();
  return <main className="min-h-screen px-6 py-8"><section className="theme-panel mx-auto max-w-5xl rounded-[28px] px-6 py-8">
    <Link href="/stud-contracts" className="theme-secondary-button inline-flex rounded-xl px-3 py-2 text-sm font-semibold">Back to My Stud Contracts</Link>
    <p className="theme-label mt-6 text-sm uppercase tracking-[0.22em]">Read-only contract record</p>
    <h1 className="theme-heading mt-2 text-4xl font-bold">{contract.sire.name} × {contract.dam.name}</h1><p className="theme-copy mt-2">{contract.role} · {contract.lifecycleLabel}</p>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="theme-card rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Contracting parties</h2><p className="theme-copy mt-3 text-sm"><Link href={`/dogs/${contract.sire.id}`} className="underline">{contract.sire.name}</Link> · {contract.kennels.sire.name}<br /><Link href={`/dogs/${contract.dam.id}`} className="underline">{contract.dam.name}</Link> · {contract.kennels.dam.name}<br />Requested: {formatDate(contract.requestedAt)}<br />Accepted: {formatDate(contract.acceptedAt)}</p></section><section className="theme-card rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Immutable agreement</h2><p className="theme-copy mt-3 text-sm">{contract.compensationSummary}. {contract.puppyTermsSummary ?? "No Puppy Back terms."}<br />Approval: {contract.terms.approvalMode}. Brucellosis: {contract.terms.brucellosisNegativeRequired ? "Required" : "Not required"}. Title: {contract.terms.titleRequirement === "NONE" ? "Not required" : contract.terms.titleRequirement === "CH_OR_HIGHER" ? "CH or higher" : "GCH or higher"}.<br />Health: {contract.terms.healthRequirements.filter((item) => item.requirementLevel !== "NONE").map((item) => `${item.healthTestCode} ${item.requirementLevel === "GREEN_ONLY" ? "green only" : "green/yellow"}`).join("; ") || "No per-test requirements"}.<br />No-litter Return Service: {contract.terms.noLitterReturnService ? "Offered" : "Not offered"}. Small-litter threshold: {contract.terms.smallLitterReturnThreshold ?? "Not offered"}.</p></section></div>
    <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Breeding and whelp outcome</h2><p className="theme-copy mt-3 text-sm">Original breeding: {contract.outcome.originalAttempt ? contract.outcome.originalAttempt.status.replaceAll("_", " ") : "Not started"}. Puppies born alive at whelping: {contract.outcome.liveBornPuppyCount ?? "Not recorded"}. Puppy Back minimum: {contract.outcome.puppyBackMinimumMet === null ? "Not applicable" : contract.outcome.puppyBackMinimumMet ? "Met" : "Not met"}. Small-Litter Return Service: {contract.outcome.smallLitterReturnServiceMet === null ? "Not applicable" : contract.outcome.smallLitterReturnServiceMet ? "Met" : "Not met"}.</p></section>
    {contract.puppySelection ? <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Puppy Back history</h2><p className="theme-copy mt-3 text-sm">Status: {contract.puppySelection.status.replaceAll("_", " ")}. {contract.puppySelection.deadlineAt ? `Deadline: ${formatDate(contract.puppySelection.deadlineAt)}.` : ""} {contract.puppySelection.completedAt ? `Completed: ${formatDate(contract.puppySelection.completedAt)}.` : ""} {contract.puppySelection.selectedDog ? `Selected puppy: ${contract.puppySelection.selectedDog.name}.` : ""}</p></section> : null}
    {contract.returnService ? <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Return Service history</h2><p className="theme-copy mt-3 text-sm">{contract.returnService.label}. Trigger: {contract.returnService.trigger}. Available: {formatDate(contract.returnService.availableAt)}. Expires: {formatDate(contract.returnService.expiresAt)} (real time). {contract.returnService.usedAt ? `Used: ${formatDate(contract.returnService.usedAt)}.` : ""} {contract.returnService.extinguishedAt ? `Ended: ${formatDate(contract.returnService.extinguishedAt)}.` : ""} {contract.returnService.returnAttempt ? `Return breeding: ${contract.returnService.returnAttempt.status.replaceAll("_", " ")}.` : ""}</p>{contract.isDamContractingKennel && contract.returnService.status === "AVAILABLE" ? <StudContractReturnServiceAction returnServiceId={contract.returnService.id} expiresAt={contract.returnService.expiresAt} /> : null}</section> : null}
  </section></main>;
}
