import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { StudContractReturnServiceAction } from "@/components/stud-contract/StudContractReturnServiceAction";
import { epochToDate } from "@/lib/gameClock";
import { getSessionUserId } from "@/lib/session";
import { getKennelForUser } from "@/server/services/kennel.service";
import { getStudContractHistoryDetail } from "@/server/services/studContractHistory.service";

const dates = new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" });
const formatDate = (value: string | null) => value ? dates.format(new Date(value)) : "Not recorded";
const formatGameDate = (value: number | null) => value === null ? "Not recorded" : dates.format(epochToDate(value));

function breedingStatusLabel(status: string) {
  const labels: Record<string, string> = {
    INITIATED: "Pregnancy pending", CHECKED_NOT_PREGNANT: "No litter", PREGNANT: "Pregnant", WHELPED: "Whelped",
    REPRODUCTIVE_EMERGENCY: "Breeding ended", FAILED: "Breeding ended", CANCELLED: "Breeding ended",
  };
  return labels[status] ?? "Breeding attempted";
}

export default async function StudContractDetailPage({ params }: { params: Promise<{ contractId: string }> }) {
  const userId = await getSessionUserId(); if (!userId) redirect("/login");
  const kennel = await getKennelForUser(userId); if (!kennel) redirect("/onboarding");
  const { contractId } = await params;
  const contract = await getStudContractHistoryDetail({ kennelId: kennel.id, contractId });
  if (!contract) notFound();
  return <main className="min-h-screen px-6 py-8"><section className="theme-panel mx-auto max-w-5xl rounded-[28px] px-6 py-8">
    <Link href="/stud-contracts" className="theme-secondary-button inline-flex rounded-xl px-3 py-2 text-sm font-semibold">Back to My Stud Contracts</Link>
    <p className="theme-label mt-6 text-sm uppercase tracking-[0.22em]">Read-only contract record</p>
    <h1 className="theme-heading mt-2 text-4xl font-bold">{contract.sire.name} × {contract.dam.name}</h1>
    <p className="theme-copy mt-2">{contract.role} · Status: {contract.lifecycleLabel} · {contract.currentState}</p>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="theme-card rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Contracting parties</h2><dl className="theme-copy mt-3 grid gap-2 text-sm"><div><dt className="theme-label">Sire</dt><dd><Link href={`/dogs/${contract.sire.id}`} className="underline">{contract.sire.name}</Link> · {contract.kennels.sire.name}</dd></div><div><dt className="theme-label">Dam</dt><dd><Link href={`/dogs/${contract.dam.id}`} className="underline">{contract.dam.name}</Link> · {contract.kennels.dam.name}</dd></div></dl></section><section className="theme-card rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Immutable agreement</h2><p className="theme-copy mt-3 text-sm">{contract.compensationSummary}. {contract.puppyTermsSummary ?? "No Puppy Back terms."}<br />Approval: {contract.terms.approvalMode}. Brucellosis: {contract.terms.brucellosisNegativeRequired ? "Required" : "Not required"}. Title: {contract.terms.titleRequirement === "NONE" ? "Not required" : contract.terms.titleRequirement === "CH_OR_HIGHER" ? "CH or higher" : "GCH or higher"}.<br />Health: {contract.terms.healthRequirements.filter((item) => item.requirementLevel !== "NONE").map((item) => `${item.healthTestCode} ${item.requirementLevel === "GREEN_ONLY" ? "green only" : "green/yellow"}`).join("; ") || "No per-test requirements"}.<br />No-litter Return Service: {contract.terms.noLitterReturnService ? "Offered" : "Not offered"}. Small-litter threshold: {contract.terms.smallLitterReturnThreshold ?? "Not offered"}.</p></section></div>
    <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Important dates</h2><dl className="theme-copy mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="theme-label">Requested</dt><dd>{formatDate(contract.requestedAt)}</dd></div>{contract.approvalDeadlineAt ? <div><dt className="theme-label">Approval deadline</dt><dd>{formatDate(contract.approvalDeadlineAt)} (real time)</dd></div> : null}{contract.acceptedAt ? <div><dt className="theme-label">Accepted</dt><dd>{formatDate(contract.acceptedAt)}</dd></div> : null}{contract.declinedAt ? <div><dt className="theme-label">Declined</dt><dd>{formatDate(contract.declinedAt)}</dd></div> : null}{contract.expiredAt ? <div><dt className="theme-label">Expired</dt><dd>{formatDate(contract.expiredAt)}</dd></div> : null}</dl></section>
    <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Breeding and whelp outcome</h2><dl className="theme-copy mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="theme-label">Original breeding</dt><dd>{contract.outcome.originalAttempt ? breedingStatusLabel(contract.outcome.originalAttempt.status) : "Not started"}</dd></div>{contract.outcome.originalAttempt ? <><div><dt className="theme-label">Breeding initiated</dt><dd>{formatGameDate(contract.outcome.originalAttempt.createdEpoch)} (game time)</dd></div>{contract.outcome.originalAttempt.checkedEpoch !== null ? <div><dt className="theme-label">Pregnancy outcome checked</dt><dd>{formatGameDate(contract.outcome.originalAttempt.checkedEpoch)} (game time)</dd></div> : null}{contract.outcome.originalAttempt.whelpedEpoch !== null ? <div><dt className="theme-label">Litter born</dt><dd>{formatGameDate(contract.outcome.originalAttempt.whelpedEpoch)} (game time)</dd></div> : null}</> : null}<div><dt className="theme-label">Puppies born alive at whelping</dt><dd>{contract.outcome.liveBornPuppyCount ?? "Not recorded"}</dd></div><div><dt className="theme-label">Puppy Back minimum</dt><dd>{contract.outcome.puppyBackMinimumMet === null ? "Not applicable" : contract.outcome.puppyBackMinimumMet ? "Met" : "Not met"}</dd></div><div><dt className="theme-label">Small-Litter Return Service</dt><dd>{contract.outcome.smallLitterReturnServiceMet === null ? "Not applicable" : contract.outcome.smallLitterReturnServiceMet ? "Met" : "Not met"}</dd></div></dl></section>
    {contract.puppySelection ? <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Puppy Back history</h2><dl className="theme-copy mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="theme-label">Status</dt><dd>{contract.puppySelection.label}</dd></div>{contract.puppySelection.openedAt ? <div><dt className="theme-label">Selection opened</dt><dd>{formatDate(contract.puppySelection.openedAt)}</dd></div> : null}{contract.puppySelection.deadlineAt ? <div><dt className="theme-label">Selection deadline</dt><dd>{formatDate(contract.puppySelection.deadlineAt)}</dd></div> : null}{contract.puppySelection.damFirstPickForfeitedAt ? <div><dt className="theme-label">Dam protected pick forfeited</dt><dd>{formatDate(contract.puppySelection.damFirstPickForfeitedAt)}</dd></div> : null}{contract.puppySelection.studSelectionForfeitedAt ? <div><dt className="theme-label">Stud selection forfeited</dt><dd>{formatDate(contract.puppySelection.studSelectionForfeitedAt)}</dd></div> : null}{contract.puppySelection.selectedDog ? <div><dt className="theme-label">Selected puppy</dt><dd><Link href={`/dogs/${contract.puppySelection.selectedDog.id}`} className="underline">{contract.puppySelection.selectedDog.name}</Link></dd></div> : null}{contract.puppySelection.completedAt ? <div><dt className="theme-label">Puppy transfer completed</dt><dd>{formatDate(contract.puppySelection.completedAt)}</dd></div> : null}</dl></section> : null}
    {contract.returnService ? <section className="theme-card mt-4 rounded-2xl p-5"><h2 className="theme-heading text-xl font-semibold">Return Service history</h2><dl className="theme-copy mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="theme-label">Status</dt><dd>{contract.returnService.label}</dd></div><div><dt className="theme-label">Trigger</dt><dd>{contract.returnService.trigger}</dd></div><div><dt className="theme-label">Available</dt><dd>{formatDate(contract.returnService.availableAt)}</dd></div><div><dt className="theme-label">Return Service expires</dt><dd>{formatDate(contract.returnService.expiresAt)} (real time)</dd></div>{contract.returnService.usedAt ? <div><dt className="theme-label">Return Service used</dt><dd>{formatDate(contract.returnService.usedAt)}</dd></div> : null}{contract.returnService.extinguishedAt ? <div><dt className="theme-label">Return Service ended</dt><dd>{formatDate(contract.returnService.extinguishedAt)}</dd></div> : null}{contract.returnService.returnAttempt ? <div><dt className="theme-label">Return breeding</dt><dd>{breedingStatusLabel(contract.returnService.returnAttempt.status)}</dd></div> : null}</dl>{contract.isDamContractingKennel && contract.returnService.status === "AVAILABLE" && contract.returnService.isActionable ? <StudContractReturnServiceAction returnServiceId={contract.returnService.id} expiresAt={contract.returnService.expiresAt} canAttempt={contract.returnService.canAttempt} unavailableReason={contract.returnService.unavailableReason} /> : null}</section> : null}
  </section></main>;
}
