import {
  ANNUAL_EVENT_HOUR_IN_YEAR,
  SHOW_DAY_FRI,
  SHOW_DAY_MON,
  SHOW_DAY_SAT,
  SHOW_DAY_SUN,
} from "./time.constants";

export const SHOW_CLUSTERS_PER_WEEK = 3;
export const SHOW_DISTRICT_COUNT = 15;
export const SHOW_CLUSTERS_PER_DISTRICT_PER_YEAR = 10;
export const SHOW_FOUR_DAY_CLUSTERS_PER_DISTRICT_PER_YEAR = 2;
export const SHOW_REGULAR_WEEK_COUNT = 51;
export const SHOW_REDUCED_CLUSTER_WEEK_INTERVAL = 17;
export const SHOW_INSTANCE_GENERATION_HORIZON_HOURS = 120;
export const SHOW_ENTRY_OPEN_LEAD_HOURS = 21;
export const SHOW_ENTRY_CLOSE_OFFSET_HOURS = 7;

export const SHOW_CLUSTER_2_DAY_RATIO = 0.8;
export const SHOW_CLUSTER_4_DAY_RATIO = 0.2;

export const SHOW_ANNUAL_EVENT_HOUR_IN_YEAR = ANNUAL_EVENT_HOUR_IN_YEAR;

export const TWO_DAY_CLUSTER_DAY_OFFSETS = [
  SHOW_DAY_SAT,
  SHOW_DAY_SUN,
] as const;

export const FOUR_DAY_CLUSTER_DAY_OFFSETS = [
  SHOW_DAY_MON,
  SHOW_DAY_FRI,
  SHOW_DAY_SAT,
  SHOW_DAY_SUN,
] as const;
