import Link from "next/link";

import type { DogProfileDto } from "@/server/mappers/dog.mapper";
import { PHENOTYPE_HEALTH_SEVERITY_TEXT_CLASSES } from "./phenotypeHealthPresentation";
import TraitLine from "@/components/ui/TraitLine";

export default function DogProfileReadSections({ profile }: { profile: DogProfileDto }) {
  const { header, snapshot, qualityAndPresentation, healthTesting, titlesAndShowCareer, pedigree, breedingAndProduction } = profile;
  return <div className="mt-12 space-y-12">
    <section aria-labelledby="ring-evaluation-heading"><p className="theme-label text-xs font-semibold uppercase tracking-[0.18em]">Ring Evaluation</p><h2 id="ring-evaluation-heading" className="theme-heading mt-2 text-3xl font-semibold">Conformation &amp; Presentation</h2><p className="theme-copy mt-3 text-sm leading-7">Visible ring categories retain ShowRing&apos;s directional player-facing values.</p><div className="mt-8 grid gap-x-12 gap-y-8 lg:grid-cols-2">{qualityAndPresentation.visibleCategories.map((category) => <TraitLine key={category.key} label={category.label} value={category.numericScore} min={category.min} max={category.max} ideal={category.ideal} leftLabel={category.leftLabel} centerLabel={category.centerLabel} rightLabel={category.rightLabel} precision={category.key === "conditioningHandling" ? 1 : 3} />)}</div></section>
    <div className="grid gap-x-12 lg:grid-cols-2">
      <section className="border-t border-[var(--color-border)] py-8" aria-labelledby="health-heading"><p className="theme-label text-xs font-semibold uppercase tracking-[0.18em]">{healthTesting.summaryLabel}</p><h2 id="health-heading" className="theme-heading mt-2 text-2xl font-semibold">Health</h2><dl className="mt-5 divide-y divide-[var(--color-border)]">{healthTesting.tests.map((test) => <div key={test.testCode} className="grid gap-1 py-4 sm:grid-cols-[minmax(10rem,0.7fr)_minmax(0,1fr)] sm:gap-5"><dt className="theme-copy text-sm">{test.displayName}</dt><dd><div className={`text-sm font-semibold ${test.severityKey ? PHENOTYPE_HEALTH_SEVERITY_TEXT_CLASSES[test.severityKey] : "theme-heading"}`}>{test.resultLabel ?? "Not tested"}</div><div className="theme-copy mt-1 text-xs leading-5">{test.testedDateLabel ?? test.minimumAgeLabel}</div></dd></div>)}{healthTesting.breedingSafetyScreening.map((screening) => <div key={screening.screeningCode} className="grid gap-1 py-4 sm:grid-cols-[minmax(10rem,0.7fr)_minmax(0,1fr)] sm:gap-5"><dt className="theme-copy text-sm">{screening.label}</dt><dd><div className="theme-heading text-sm font-semibold">{screening.currentStatusLabel}</div><div className="theme-copy mt-1 text-xs leading-5">{screening.validUntilLabel ?? screening.testedAtLabel ?? screening.helperText}</div></dd></div>)}</dl></section>
      <section className="border-t border-[var(--color-border)] py-8" aria-labelledby="show-career-heading"><p className="theme-label text-xs font-semibold uppercase tracking-[0.18em]">{titlesAndShowCareer.summaryLabel}</p><h2 id="show-career-heading" className="theme-heading mt-2 text-2xl font-semibold">Show Career</h2><dl className="mt-5 divide-y divide-[var(--color-border)]"><div className="py-4"><dt className="theme-copy text-sm">Champion progress</dt><dd className="theme-heading text-sm font-semibold">{titlesAndShowCareer.pointsEarned}/{titlesAndShowCareer.pointsRequired} points · {titlesAndShowCareer.majorsEarned}/{titlesAndShowCareer.majorsRequired} majors</dd></div><div className="py-4"><dt className="theme-copy text-sm">Grand Champion progress</dt><dd className="theme-heading text-sm font-semibold">{titlesAndShowCareer.grandPointsLabel} · {titlesAndShowCareer.grandMajorsEarned}/{titlesAndShowCareer.grandMajorsRequired} majors</dd></div><div className="py-4"><dt className="theme-copy text-sm">Latest result</dt><dd className="theme-heading text-sm font-semibold">{titlesAndShowCareer.recentShowResults[0]?.showName ?? "No completed show results yet."}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><Link href={titlesAndShowCareer.fullShowRecordUrl} className="theme-secondary-button rounded-xl px-4 py-2 text-sm font-semibold">View Full Show Record</Link><Link href={`/dogs/${header.dogId}/ribbon-room`} className="theme-secondary-button rounded-xl px-4 py-2 text-sm font-semibold">Ribbon Room</Link></div></section>
      <section className="border-t border-[var(--color-border)] py-8" aria-labelledby="pedigree-heading"><p className="theme-label text-xs font-semibold uppercase tracking-[0.18em]">{pedigree.healthTestsSummary}</p><h2 id="pedigree-heading" className="theme-heading mt-2 text-2xl font-semibold">Pedigree</h2><p className="theme-copy mt-4 text-sm leading-6">{pedigree.coiLabel} · {snapshot.originLabel}</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{pedigree.ancestors.slice(0, 4).map((dog) => <Link key={dog.dogId} href={dog.profileUrl} className="dog-card rounded-xl px-4 py-3 text-sm"><span className="theme-heading font-semibold">{dog.relationship}: {dog.displayName}</span><span className="theme-copy mt-1 block text-xs">{dog.healthTestsSummary}</span></Link>)}</div><Link href={`/dogs/${header.dogId}/pedigree`} className="theme-secondary-button mt-5 inline-flex rounded-xl px-4 py-2 text-sm font-semibold">View Full Pedigree</Link></section>
      <section className="border-t border-[var(--color-border)] py-8" aria-labelledby="breeding-heading"><p className="theme-label text-xs font-semibold uppercase tracking-[0.18em]">{breedingAndProduction.productionRoleLabel}</p><h2 id="breeding-heading" className="theme-heading mt-2 text-2xl font-semibold">Breeding &amp; Production</h2><p className="theme-copy mt-4 text-sm leading-6">{snapshot.reproductiveStatus?.detail ?? snapshot.breedingEligibilityLabel}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="dog-card rounded-xl p-4 text-sm"><div className="theme-copy">Producer merit</div><div className="theme-heading mt-1 font-semibold">{breedingAndProduction.producerMerit.progressLabel}</div></div><div className="dog-card rounded-xl p-4 text-sm"><div className="theme-copy">Champion offspring</div><div className="theme-heading mt-1 font-semibold">{breedingAndProduction.championOffspringCount}</div></div></div>{breedingAndProduction.progeny.length ? <div className="mt-4 grid gap-2">{breedingAndProduction.progeny.map((dog) => <Link key={dog.dogId} href={dog.dogUrl} className="theme-copy text-sm underline">{dog.displayName} · {dog.sexLabel}</Link>)}</div> : null}</section>
    </div>
  </div>;
}
